using System;
using System.Reflection;
using System.Security;


[assembly: AssemblyTitle("LLBLGen Pro Dynamic Query Engine for Sybase ASA iAnywhere")]
[assembly: AssemblyDescription("Dynamic Query Engine to use within code generated by LLBLGen Pro, to target Sybase ASA iAnywhere instances")]
[assembly: AssemblyConfiguration(".NET 3.5 or higher")]

[assembly: AssemblyCompany("Solutions Design bv")]
[assembly: AssemblyProduct("LLBLGen Pro")]
[assembly: AssemblyCopyright("(c)2002-2016 Solutions Design. All rights reserved.")]
[assembly: AssemblyTrademark("LLBLGen and LLBLGen Pro are trademarks of Solutions Design.")]
[assembly: AssemblyCulture("")]
[assembly: CLSCompliant(true)]

[assembly: AllowPartiallyTrustedCallers()]
[assembly: AssemblyVersion("5.0.0.0")]
[assembly: AssemblyFileVersion("5.0.0")]
[assembly: AssemblyDelaySign(false)]
